import React, { useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import { BrowserRouter, Link, Route, Routes, useNavigate, useParams } from "react-router-dom";
import axios from "axios";
import "./styles.css";

const api = axios.create({ baseURL: "http://127.0.0.1:8638", withCredentials: true });
const empty = { property_title:"", property_location:"", submitter_email:"", property_description:"", property_category:"Apartment", terms_accepted:true };
const fields = [["property_title","Property title"],["property_location","Property location"],["submitter_email","Submitter email"]];

function Login({ setAuth }) { const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [register,setRegister]=useState(false); const [error,setError]=useState("");
  async function submit(e){e.preventDefault();setError("");try{let r=await api.post(register?"/auth/register":"/auth/login",register?{name:email.split("@")[0],email,password}:{email,password});if(register){r=await api.post("/auth/login",{email,password});}setAuth(r.data);setEmail("");setPassword("");}catch(err){setError(err.response?.data?.detail||"Request failed");}}
  return <form className="login" onSubmit={submit}><strong>{register?"Create account":"Login"}</strong><input placeholder="email" type="email" value={email} onChange={e=>setEmail(e.target.value)} required/><input placeholder="password" type="password" value={password} onChange={e=>setPassword(e.target.value)} required/><button>{register?"Register":"Login"}</button><button type="button" onClick={()=>setRegister(!register)}>{register?"Use login":"Register"}</button>{error&&<span>{error}</span>}</form>;
}
function Form({ initial=empty, onSubmit, label }) { const [form,setForm]=useState(initial); const set=(k,v)=>setForm({...form,[k]:v}); return <form className="form" onSubmit={e=>{e.preventDefault();onSubmit(form)}}>{fields.map(([key,name])=><label key={key}>{name}<input required value={form[key]} onChange={e=>set(key,e.target.value)}/></label>)}<label>Category<select value={form.property_category} onChange={e=>set("property_category",e.target.value)}>{["Apartment","House","Condo","Townhouse"].map(x=><option key={x}>{x}</option>)}</select></label><label>Description<textarea required minLength="26" value={form.property_description} onChange={e=>set("property_description",e.target.value)}/></label><button>{label}</button></form> }
function App(){const [auth,setAuth]=useState(null);const [rows,setRows]=useState([]);const navigate=useNavigate();useEffect(()=>{api.get("/auth/me").then(r=>setAuth(r.data)).catch(()=>setAuth(null))},[]);useEffect(()=>{if(auth)api.get("/listings").then(r=>setRows(r.data))},[auth]);async function logout(){await api.post("/auth/logout");setAuth(null);setRows([]);navigate("/")}async function save(data){const r=await api.post("/listings",data);setRows([...rows,r.data]);navigate("/")}async function update(id,data){const r=await api.put(`/listings/${id}`,data);setRows(rows.map(x=>x.id===id?r.data:x));navigate("/")}async function remove(id){await api.delete(`/listings/${id}`);setRows(rows.filter(x=>x.id!==id));navigate("/")}return <main><header><Link to="/">Rental Housing Listings</Link>{auth?<><Link to="/create">Add record</Link><button onClick={logout}>Logout</button></>:<span>Login required for records</span>}</header><Login setAuth={setAuth}/><Routes><Route path="/" element={auth?<table><thead><tr><th>ID</th><th>Title</th><th>Location</th><th>Category</th><th>Actions</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td>{x.id}</td><td>{x.property_title}</td><td>{x.property_location}</td><td>{x.property_category}</td><td><Link to={`/update/${x.id}`}>Update</Link> <Link to={`/delete/${x.id}`}>Delete</Link></td></tr>)}</tbody></table>:<h2>Login required</h2>}/><Route path="/create" element={auth?<Form label="Add listing" onSubmit={save}/>:<h2>Login required</h2>}/><Route path="/update/:id" element={auth?<Edit rows={rows} onSubmit={update}/>:<h2>Login required</h2>}/><Route path="/delete/:id" element={auth?<Delete rows={rows} onDelete={remove}/>:<h2>Login required</h2>}/></Routes></main>}
function Edit({rows,onSubmit}){const {id}=useParams();const row=rows.find(x=>x.id===Number(id));return row?<Form initial={row} label="Update listing" onSubmit={x=>onSubmit(Number(id),x)}/>:<h2>Loading record...</h2>}
function Delete({rows,onDelete}){const {id}=useParams();const row=rows.find(x=>x.id===Number(id));return row?<section><h2>Delete {row.property_title}?</h2><button onClick={()=>onDelete(Number(id))}>Delete listing</button></section>:<h2>Loading record...</h2>}
createRoot(document.getElementById("root")).render(<BrowserRouter><App/></BrowserRouter>);
